name = "OmniverseMakie"
uuid = "d60c73f4-20f1-48ea-a3b4-a683962494cb"
version = "0.1.0"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>"]

[workspace]
projects = ["lib/LibOVRTX"]

[deps]
LibOVRTX = "48e69356-47aa-4e0c-8089-4409475c3dd9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[sources]
LibOVRTX = {path = "lib/LibOVRTX"}

[compat]
LibOVRTX = "0.1"
julia = "1.12"
